<footer>
    <div class="social-box">
        <ul>
            <li>
                <a href="https://fr-fr.facebook.com/" target="_blank">
                    <i class="fa-brands fa-facebook-f"></i>
                </a>
            </li>
            <li>
                <a href="https://www.instagram.com/" target="_blank">
                    <i class="fa-brands fa-instagram"></i>
                </a>
            </li>
            <li>
                <a href="https://twitter.com/" target="_blank">
                    <i class="fa-brands fa-twitter"></i>
                </a>
            </li>
        </ul>
    </div>
    <div class="footer-menu">
        <ul>
            <li>
                <a href="index.php?page=articles">Articles</a>
            </li>
            <li>
                <a href="index.php?page=albums">Albums</a>
            </li>
            <li>
                <a href="index.php?page=artists">Artists</a>
            </li>
        </ul>
    </div>
    <div class="footer-bottom">
        <div class="copyright">
            <p>© KY - All rights reserved 2022</p>
        </div>
        <div class="accessibility">
            <div id="accessibility-container" class="hidden-accessibility">
                <div class="accessibility-btn">
                    <div  class="dark-container">
                        <button id="darkModeBtn" class="dark-btn">Dark Mode</button>
                    </div>
                    <div class="charsize-container">
                        <button id="increaseCharSizeBtn" class="charsize-btn">A+</button>
                        <button id="defaultCharSizeBtn" class="charsize-btn">A</button>
                        <button id="decreaseCharSizeBtn" class="charsize-btn">A-</button>
                    </div>
                </div>
            </div><!-- 
            <a accessibility-link href="#">Accessibility</a> -->
            <button id="accessibility-link">Accessibility</button>
        </div>
    </div>
</footer>

<script type="module" src="./js/script.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</body>

</html>