<!doctype html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" type="text/css" />
    <link rel="stylesheet" href="./css/normalize.css" type="text/css" />
    <link rel="stylesheet" href="./css/style.css" type="text/css" />
    <title>KY</title>
</head>

<body>
    <header>
        <div class="nav-box">
            <nav>
                <div class="navbar">
                    <div class="navbar-container">
                        <input class="checkbox" type="checkbox"/>
                        <div class="hamburger-lines">
                            <span class="line line1"></span>
                            <span class="line line2"></span>
                            <span class="line line3"></span>
                        </div>
                        <div class="logo">
                            <a href="index.php">
                                <img src="./asset/img/ky_logo.png" alt="logo KY">
                            </a>
                        </div>
                        <div class="log-container">
                            <?php if (empty($_SESSION)) : ?>
                                <a href="index.php?page=login" class="log-link">Login</a>
                                <a href="index.php?page=register" class="log-link">Sign up</a>
                            <?php endif ?>
                            <div class="account-container">
                                <?php if (isset($_SESSION['username'])) : ?>
                                    <a href="#">
                                        <i class="fa-solid fa-user"></i>ACCOUNT
                                    </a>
                                    <ul>
                                        <li>
                                            <a href="index.php?page=account">My account</a>
                                        </li>
                                        <li>
                                            <a href="index.php?page=logout">Logout</a>
                                        </li>
                                        <?php if ($_SESSION['access_admin'] === true) : ?>
                                            <li>
                                                <a href="index.php?page=back">Back-office</a>
                                            </li>
                                        <?php endif ?>
                                    </ul>
                                <?php endif ?>
                            </div>
                        </div>
                        <div class="menu-items">
                            <ul>
                                <li>
                                    <a href="index.php?page=articles">Articles</a>
                                </li>
                                <li>
                                    <a href="index.php?page=albums">Albums</a>
                                </li>
                                <li>
                                    <a href="index.php?page=artists">Artists</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </nav>
        </div>
    </header>