<section class="newsletter-section">
    <div class="newsletter-container">
        <div class="newsletter-left">
            <div class="newsletter-logo-container">
                <img src="./asset/img/ky_logo.png" alt="logo KY">
            </div>
            <div class="newsletter-title">
                <h3>Subscribe to our newsletter</h3>
            </div>
        </div>
        <form class="newsletter-form-container" method='post'>
            <?= $newsletterForm->init() ?>
        </form>
    </div>
</section>